version: '3.8'
networks:
  pos:
services:
  nginx_pos:
    image: nginx:alpine
    container_name: nginx_pos
    ports:
      - '8040:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - pos
      - pos_db
    networks:
      - pos

  pos_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'dimas'
      POSTGRES_PASSWORD: 'dimasw1950'
      POSTGRES_DB: 'pos'
    ports:
      - '5435:5432'
    networks:
      - pos

  pos:
    container_name: pos
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - pos